version: '3'

volumes:
  mongodbdata:
    name: mongodbdata
    driver: local

services:
  server:
    build: .
    # ? using the Dockerfile in the "." directory, build the image
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/app
      # ? map the current directory "." to the "/app" directory in docker (app chính là WORKDIR trong Dockerfile)
      - /app/node_modules
      # ? map docker's node_modules seperately
    command: npm run start:docker

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file: [.env] # copy the .env file to the .env file of the container, to work with mongo-init.sh
    volumes: 
      # sync the volume calls mongodbdata to the /data/db of the mongodb container
      # (the /data/db dir holds the actual data of mongodb)
      - mongodbdata:/data/db

      # syntax to mount the file to the container directory
      # <local dir>:<container_dir>:<optional access (example `ro`- read-only)>
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    
  services:
  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:8081"
    environment:
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}